### ISSUE TITLE
您好，这个项目官方说的安装步骤都试过了，不知道为什么无法看到地址

### ISSUE THREAD

**Issue by jackylee1** [tongpi/DeepVideoAnalytics--document#1]
您好，这个项目官方说的安装步骤都试过了，不知道为什么无法看到地址。还要自己搭建服务器的吗

**Comment by doudoubean** [comment]
安装官方文档操作，即可。确保项目运行成功，在浏览器端访问即可。

**Comment by jackylee1** [comment]
dva-pg is up-to-date
dva-redis is up-to-date
dva-rmq is up-to-date
Starting webserver ... done



Checking if DVA server is running, waiting for another minute and at most 19 minutes
Checking if DVA server is running, waiting for another minute and at most 18 minutes
Checking if DVA server is running, waiting for another minute and at most 17 minutes
Checking if DVA server is running, waiting for another minute and at most 16 minutes
每次这个运行完就什么都没有了

**Comment by doudoubean** [comment]
你提供的信息太少，无法判断错误原因。建议你查看日志，通过日志查看具体问题。

**Comment by jackylee1** [comment]
anbangleedeMacBook-Air:DeepVideoAnalytics-master-2 anbanglee$ python manage.py start dev --init_models https://gist.githubusercontent.com/AKSHAYUBHAT/5adccb7070a921ec244b3b524222d65b/raw/881de719510d7452d7f9915a6a938d1a05a91c15/models.json 
Checking if docker-compose is available
Starting deploy/dev/docker-compose.yml
  Name                Command              State               Ports            
--------------------------------------------------------------------------------
dva-pg      docker-entrypoint.sh           Up       5432/tcp                    
            postgres                                                            
dva-redis   /app-entrypoint.sh /run.sh     Up       6379/tcp                    
dva-rmq     docker-entrypoint.sh rabbi     Up       25672/tcp, 4369/tcp,        
            ...                                     5671/tcp, 5672/tcp          
webserver   bash -c cd /root/DVA/repos     Exit 1                               
            ...                                                                 
Pulling/Refreshing container images, first time it might take a while to download the image
latest: Pulling from akshayubhat/dva-auto
1be7f2b886e8: Already exists 
6fbc4a21b806: Already exists 
c71a6f8e1378: Already exists 
4be3072e5a37: Already exists 
06c6d2f59700: Already exists 
8cdf75855ef8: Already exists 
ad437d4eaf95: Already exists 
3408fc9c1eb2: Already exists 
379e6caf6509: Already exists 
7c16be936e39: Already exists 
e85e7d35addc: Already exists 
e7b5810aa9e9: Already exists 
6cbe37b699ae: Already exists 
0e9567273148: Already exists 
c69ea456d68f: Already exists 
3adb921abdda: Already exists 
2a8a14afc6b5: Already exists 
08c3ca19bf2f: Already exists 
c414230a9cd0: Already exists 
856167d3feb6: Already exists 
f9cfac0a7410: Already exists 
e04470f28252: Already exists 
a05331ea2dd9: Already exists 
57fccbe3a2d7: Already exists 
7595d824edff: Already exists 
98a256406aa0: Already exists 
c69329c1cd05: Already exists 
be043685eb20: Already exists 
a52d5ac0f05e: Already exists 
003b40c7efbd: Already exists 
a427074e6ed3: Already exists 
1e0964afb6e0: Already exists 
245b231377a6: Already exists 
9d8dd8e28e88: Already exists 
a6c5aa7c0375: Already exists 
09a8097738f8: Already exists 
2210dd95d844: Already exists 
873cf4f37f6a: Already exists 
2cbeed167de6: Already exists 
9b5e3848c844: Already exists 
b311d641f780: Already exists 
1853656e07d2: Already exists 
1feedc719372: Already exists 
ceb744fd6f58: Already exists 
996a7b043708: Already exists 
Digest: sha256:ddbec6ef9c3c5df472d4c454fc3a8bf4f855fd826c26ab57db464cd01afa1db0
Status: Image is up to date for akshayubhat/dva-auto:latest
Trying to launch containers
docker-compose -f docker-compose.yml up -d
Checking if DVA server is running, waiting for another minute and at most 20 minutes
dva-pg is up-to-date
dva-rmq is up-to-date
dva-redis is up-to-date
Starting webserver ... done
Checking if DVA server is running, waiting for another minute and at most 19 minutes
Checking if DVA server is running, waiting for another minute and at most 18 minutes
Checking if DVA server is running, waiting for another minute and at most 17 minutes
Checking if DVA server is running, waiting for another minute and at most 16 minutes
Checking if DVA server is running, waiting for another minute and at most 15 minutes
Checking if DVA server is running, waiting for another minute and at most 14 minutes
Checking if DVA server is running, waiting for another minute and at most 13 minutes
Checking if DVA server is running, waiting for another minute and at most 12 minutes
Checking if DVA server is running, waiting for another minute and at most 11 minutes
Checking if DVA server is running, waiting for another minute and at most 10 minutes
Checking if DVA server is running, waiting for another minute and at most 9 minutes
Checking if DVA server is running, waiting for another minute and at most 8 minutes
Checking if DVA server is running, waiting for another minute and at most 7 minutes
Checking if DVA server is running, waiting for another minute and at most 6 minutes
Checking if DVA server is running, waiting for another minute and at most 5 minutes
Checking if DVA server is running, waiting for another minute and at most 4 minutes
Checking if DVA server is running, waiting for another minute and at most 3 minutes
Checking if DVA server is running, waiting for another minute and at most 2 minutes
Checking if DVA server is running, waiting for another minute and at most 1 minutes
anbangleedeMacBook-Air:DeepVideoAnalytics-master-2 anbanglee$ docker logs webserver
running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:566:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:566:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Collecting django-debug-toolbar
  Downloading django_debug_toolbar-1.9.1-py2.py3-none-any.whl (206kB)
Requirement already satisfied: Django>=1.8 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar)
Collecting sqlparse>=0.2.0 (from django-debug-toolbar)
  Downloading sqlparse-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.8->django-debug-toolbar)
Installing collected packages: sqlparse, django-debug-toolbar
Successfully installed django-debug-toolbar-1.9.1 sqlparse-0.2.4
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_trainedmodel_uuid... OK
  Applying dvaapp.0002_trainedmodel_training_set... OK
  Applying dvaapp.0003_auto_20180120_1817... OK
  Applying dvaapp.0004_remove_trainingset_built_ts... OK
  Applying dvaapp.0005_trainingset_files... OK
  Applying dvaapp.0006_trainingset_uuid... OK
  Applying dvaapp.0007_auto_20180120_2359... OK
  Applying dvaapp.0008_auto_20180129_0719... OK
  Applying dvaapp.0009_video_stream... OK
  Applying dvaapp.0010_remove_video_youtube_video... OK
  Applying dvaapp.0011_auto_20180309_0732... OK
  Applying dvaapp.0012_auto_20180309_0755... OK
  Applying dvaapp.0013_export... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
Cloning into 'VDN'...
[I 13:51:19.375 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 13:51:19.715 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 13:51:19.904 NotebookApp] Serving notebooks from local directory: /root/DVA/docs
[I 13:51:19.905 NotebookApp] 0 active kernels
[I 13:51:19.906 NotebookApp] The Jupyter Notebook is running at:
[I 13:51:19.907 NotebookApp] http://[all ip addresses on your system]:8888/?token=10385d27058c937c12c309a9398d3bb5c111a1b37b48b869
[I 13:51:19.908 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:51:19.912 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=10385d27058c937c12c309a9398d3bb5c111a1b37b48b869
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Traceback (most recent call last):
  File "./launch_from_env.py", line 70, in <module>
    subprocess.check_output(["python", "manage.py", "collectstatic", "--no-input"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'collectstatic', '--no-input']' returned non-zero exit status -9
Traceback (most recent call last):
  File "./start_container.py", line 18, in <module>
    subprocess.check_call(['./launch_from_env.py','0'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:566:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:566:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Requirement already satisfied: django-debug-toolbar in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: Django>=1.8 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar)
Requirement already satisfied: sqlparse>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.8->django-debug-toolbar)
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
[W 16:08:34.800 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 16:08:34.990 NotebookApp] Serving notebooks from local directory: /root/DVA/docs
[I 16:08:34.991 NotebookApp] 0 active kernels
[I 16:08:34.991 NotebookApp] The Jupyter Notebook is running at:
[I 16:08:34.992 NotebookApp] http://[all ip addresses on your system]:8888/?token=4c609c0988ef0b938c7b5a83015c29b86ed6386c3fea1b91
[I 16:08:34.993 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:08:35.015 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4c609c0988ef0b938c7b5a83015c29b86ed6386c3fea1b91
Traceback (most recent call last):
  File "./launch_from_env.py", line 70, in <module>
    subprocess.check_output(["python", "manage.py", "collectstatic", "--no-input"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'collectstatic', '--no-input']' returned non-zero exit status -9
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Traceback (most recent call last):
  File "./start_container.py", line 18, in <module>
    subprocess.check_call(['./launch_from_env.py','0'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

**Comment by jackylee1** [comment]
你好，你有微信吗？可以加我一下吗？981687874
